---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-capstone
  template:
    metadata:
      labels:
        app: helloworld-capstone
    spec:
      containers:
        - name: helloworld-capstone
          image: linh626688/helloworld-capstone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80  
  selector:
    app: helloworld-capstone
  type: LoadBalancer